#!/usr/bin/env bash

function print_usage {
    echo "run_tests -- Run the tests for the Python Education exercises"
    echo ""
    echo "Arguments:"
    echo "  -h | --help: Display this help"
    echo "  --ex       : Only run tests for the given exercise [mandatory]"
    echo ""
    echo "Any other arguments are passed through to pytest."
}

ARGS=()
EXERCISE=""
while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help) print_usage; exit 0 ;;
        --ex)        EXERCISE="$2"; shift ;;
        *)           ARGS=("${ARGS[@]}" "$1") ;;
    esac
    shift
done

if [ -z "$EXERCISE" ]; then
    echo "No exercise argument specified" >&2
    print_usage >&2
    exit 1
fi

# Make the working directory be the root of the git repository
cd "$(dirname "$(realpath "$0")")"

if [ ! -d "venv" ]; then
    echo "Couldn't find the virtual environment to run the tests in - have you run ./setup_venv?" >&2
    exit 1
fi

venv/bin/python3 -m pytest "exercises/exercise$EXERCISE" "${ARGS[@]}"
